import { DB } from "@/db/types"

export const db: DB = {
  users: [
    {
      id: "1",
      username: "johndoe",
    },
    {
      id: "2",
      username: "janedoe",
    },
    {
      id: "3",
      username: "bobsmith",
    },
    {
      id: "4",
      username: "sarahjones",
    },
    {
      id: "5",
      username: "mikebrown",
    },
  ],
  groups: [
    {
      id: "1",
      name: "Viagem de férias",
      memberIds: ["1", "2", "3", "5"],
      creatorId: "1",
    },
    {
      id: "2",
      name: "Grupo de amigos",
      memberIds: ["1", "3", "4", "5"],
      creatorId: "1",
    },
  ],
  transactions: [
    {
      id: "1",
      groupId: "1",
      amount: 100,
      payerId: "1",
      payeeId: "2",
      description: "Split the bill",
    },
    {
      id: "2",
      groupId: "1",
      amount: 50,
      payerId: "2",
      payeeId: "1",
      description: "Split the bill",
    },
    {
      id: "3",
      groupId: "2",
      amount: 200,
      payerId: "1",
      payeeId: "3",
      description: "Split the bill",
    },
    {
      id: "4",
      groupId: "2",
      amount: 100,
      payerId: "3",
      payeeId: "1",
      description: "Split the bill",
    },
    {
      id: "5",
      groupId: "2",
      amount: 183,
      payerId: "1",
      payeeId: "4",
      description: "Split the bill",
    },
    {
      id: "6",
      groupId: "2",
      amount: 76,
      payerId: "4",
      payeeId: "1",
      description: "Split the bill",
    },
    {
      id: "7",
      groupId: "2",
      amount: 46,
      payerId: "1",
      payeeId: "5",
      description: "Split the bill",
    },
    {
      id: "8",
      groupId: "2",
      amount: 61,
      payerId: "5",
      payeeId: "1",
      description: "Split the bill",
    },
    {
      id: "9",
      groupId: "2",
      amount: 144,
      payerId: "1",
      payeeId: "3",
      description: "Split the bill",
    },
    {
      id: "10",
      groupId: "2",
      amount: 162,
      payerId: "3",
      payeeId: "1",
      description: "Split the bill",
    },
    {
      id: "11",
      groupId: "2",
      amount: 175,
      payerId: "1",
      payeeId: "4",
      description: "Split the bill",
    },
    {
      id: "12",
      groupId: "2",
      amount: 132,
      payerId: "4",
      payeeId: "1",
      description: "Split the bill",
    },
    {
      id: "13",
      groupId: "2",
      amount: 138,
      payerId: "1",
      payeeId: "5",
      description: "Split the bill",
    },
    {
      id: "14",
      groupId: "2",
      amount: 119,
      payerId: "5",
      payeeId: "1",
      description: "Split the bill",
    },
    {
      id: "15",
      groupId: "2",
      amount: 32,
      payerId: "1",
      payeeId: "3",
      description: "Split the bill",
    },
    {
      id: "16",
      groupId: "2",
      amount: 78,
      payerId: "3",
      payeeId: "1",
      description: "Split the bill",
    },
    {
      id: "17",
      groupId: "2",
      amount: 22,
      payerId: "1",
      payeeId: "4",
      description: "Split the bill",
    },
    {
      id: "18",
      groupId: "2",
      amount: 35,
      payerId: "4",
      payeeId: "1",
      description: "Split the bill",
    },
  ],
}
